-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 14:16:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ExGrupo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ExGrupo` ;

-- -----------------------------------------------------
-- Schema ExGrupo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExGrupo` DEFAULT CHARACTER SET utf8 ;
USE `ExGrupo` ;

-- -----------------------------------------------------
-- Table `ExGrupo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExGrupo`.`Cliente` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `dataDeNascimento` VARCHAR(10) NOT NULL,
  `numeroResidencia` INT NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `unidadeFederativa` INT NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Cliente VALUES ('08010842109','Pedro Paulo',
'Gumercindo','Centro','Terenos','pedroapsilva22@gmail.com','13/05/2002',1061,
99881718,02)